version: '2.1'

services:
  x64:
    container_name: blinky_x64
    build: .
    command: 'scripts/watch'
    ports: [ "${PORT:-9012}:9012" ]
    volumes:
      - 'go_src:/opt/go/src'
      - '.:/opt/go/src/blinky'
      - '/opt/go/src/blinky/build'

volumes:
  go_src:
