version: 2
jobs:
  build_x64: &BUILD
    docker:
      - image: fengb/blinky-x64:2017-11-14
    working_directory: /opt/go/src/blinky
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: make

  build_armv7:
    <<: *BUILD
    docker:
      - image: fengb/blinky-armv7:2017-11-14

workflows:
  version: 2
  build:
    jobs:
      - build_x64
      #- build_armv7
