#!/bin/bash

set -euo pipefail

: ${VERSION?}
: ${TARBALL?}

SHA256=$(sha256sum "${TARBALL}" | cut -d ' ' -f 1)

if [ -n "${1-}" ]; then
	exec >"$1"
fi

sed -e "s/VERSION/${VERSION}/" -e "s/SHA256/${SHA256}/" <<'EOF'
pkgname=blinky
pkgver=VERSION
pkgrel=1
pkgdesc="Monitor Pacman changes"
arch=('x86_64')
url="https://github.com/fengb/blinky"
license=('MIT')
makedepends=('go')
source=("https://github.com/fengb/blinky/archive/v${pkgver}.tar.gz")
sha256sums=('SHA256')

build() {
  cd "${srcdir}/${pkgname}-${pkgver}"
  make
}

package() {
  cd "${srcdir}/${pkgname}-${pkgver}"
  make PREFIX="${pkgdir}" install
}
EOF
