#!/bin/bash

function reap {
  pkill -g $$
  exit
}
trap "reap" EXIT

function descendant_pids {
  pgrep -g $$ | grep -v ^"$$"'$'
}

while true; do
  go run *.go &
  inotifywait -qq --include "\.go$" --event modify,create,delete .
  sleep 1 # debounce!
  kill $(descendant_pids) 2>/dev/null
  wait
done
