#!/bin/bash

function reap {
  pkill -g $$
}
trap "reap" EXIT

while true; do
  make build/blinky-dev
  build/blinky-dev &
  cid=$!
  inotifywait -qq --include "\.go$" --event modify,create,delete,attrib .
  sleep 1 # debounce!
  kill $cid 2>/dev/null
  wait
done
