#!/bin/bash

trap "exit" INT

while true; do
  if make build/blinky-dev; then
    build/blinky-dev &
  fi
  cid=$!
  inotifywait -qq --include "\.go$" --event modify,create,delete,attrib .
  sleep 1 # debounce!
  kill $cid 2>/dev/null
  wait
done
